### ISSUE TITLE
Files.createSymbolicLink will fail on windows if not running from privileged environment

### ISSUE THREAD

**Issue by hellozyemlya** [MsRandom/minecraft-codev#2]
Issue title is self-descriptive. For windows its better not to use createSymbolicLink

**Comment by MsRandom** [comment]
Oh, that's good to know. Is there a simple alternative or is the best solution simply copying the files?

**Comment by MsRandom** [comment]
`Files.createSymbolicLink` is no longer used. It might be revisited in the future but for explicit checks for windows
